import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

decorations = "Buttonless"

[font]
normal.family = "JuliaMono Nerd Font"

#regular
size = 9.5

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
dynamic_padding = true
padding.x = 0
padding.y = 4

